# Generated by Django 3.0.8 on 2020-07-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ativity',
            new_name='Activity',
        ),
        migrations.AddField(
            model_name='user',
            name='time_zone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
